---
title       : Overview of Interactive Economic Chart Viewer
subtitle    : 
author      : Stuart Cary
job         : Data Wrangler
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [bootstrap, quiz]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Overview

* The interactive economic chart viewer allows users to keep tabs on important U.S. economic trends.
* Users can select from the following three charts:
 + U.S. Unemployment Rate
 + 4-week Moving Average of U.S. Initial Unemployment Claims
 + U.S. Adjusted Financial Conditions Index

* For each series, the following years of data are available to view
```{r, echo=FALSE}
currYear <- as.numeric(format(Sys.Date(), "%Y"))
unRate <- currYear - as.numeric(format(as.Date("1948-01-01"), "%Y"))
claims <- currYear - as.numeric(format(as.Date("1967-01-28"), "%Y"))
conditions <- currYear - as.numeric(format(as.Date("1973-01-05"), "%Y"))

data.frame(Series = c("Unemployment Rate","Initial Unemployment Claims","Financial Conditions"), Years.of.Data = c(unRate,claims,conditions))

```



--- .class #id 

## Why You Should Use It

* Rather than download and plot the data yourself, you can automatically view charts for three important data sets, updated daily.
* The interative charts allow for more in-depth analysis than static charts. Users can zoom in on specific time periods to view them in greater detail
* U.S. recession are highlighted in the charts, allowing users to see how the series changed during periods of economic weakness

---

## Why It's Important

* The U.S. Unemployment Rate tells what percentage of the working population does not have a job. Giving you an idea of the health of the U.S. Economy
* The 4-week Moving Average of U.S. Initial Unemployment Claims tells you how many people have recently been fired and filed or unemployment benefits. It is closely related to the unemployment rate, but is considered a leading indicator for the U.S economy.
* The U.S. Adjusted Financial Conditions Index tells you whether financial conditions have been getting better (a lower reading) or worse (a higher reading). This is an important measure for anyone who needs to either borrow or lend money.

--- &radio

## Conclusion

* Allows you to quickly view important charts
* Charts are visually appealing and allow users to pan/zoom
* Never have to worry about updating the charts yourself!

Would you use this app?

1. _Yes - This looks amazing_
2. Maybe, I need to think about it.
3. No way

*** .hint 
Sorry, no hints available!

*** .explanation
Yes! Of course you would use this app!

